export const PREAMBLE = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// This file was generated by @anchanix/fluent-utils. !!! DO NOT MODIFY !!!
// It is recommended to commit this file to your repository.

`

export const FLUENT_BUILTIN_FUNCTIONS = ['DATETIME', 'NUMBER']
